import { Orbitron } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import SpaceDust from "@/components/SpaceDust";

const orbitron = Orbitron({
  subsets: ["latin"],
  variable: "--font-orbitron",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${orbitron.variable} font-sans antialiased`}>
        <SpaceDust />
        <Header />
        <main className="pt-24">{children}</main>
      </body>
    </html>
  );
}
